using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AESEncrypt;

namespace MLRemitWebAPI.Controllers
{
    public class ForgotPasswordController : Controller
    {
        private String encStringKey = "B905BD7BFBD902DCB115B327F9018CEA";
        private AESEncryption encdata = new AESEncryption();
        
        //
        // GET: /ForgotPassword/
        public ActionResult fprstpswrd(String e, String sc, String cid, String fn)
        {

            Random random = new Random();
            const string chars = "9AB8CD7EF6GH5IJ4KL3MN2OP1QR0ST9UV8WX7YZ6012345";
            String autoGeneratedPasswrd = new string(Enumerable.Repeat(chars, 10).Select(s => s[random.Next(s.Length)]).ToArray());

            return View();
        }
	}
}