//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.IO;
using System.Text;
using System.Xml;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.paynearme.com/api/pnm_xmlschema_v1_7")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.paynearme.com/api/pnm_xmlschema_v1_7", IsNullable = false)]
public partial class pending_payment_response
{

    private pending_payment_responsePending_payment[] pending_paymentField;

    private string versionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pending_payment")]
    public pending_payment_responsePending_payment[] pending_payment
    {
        get
        {
            return this.pending_paymentField;
        }
        set
        {
            this.pending_paymentField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.paynearme.com/api/pnm_xmlschema_v1_7")]
public partial class pending_payment_responsePending_payment
{

    private string itemField;

    private ItemChoiceType itemElementNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pnm_order_identifier", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("pnm_payment_identifier", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item
    {
        get
        {
            return this.itemField;
        }
        set
        {
            this.itemField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName
    {
        get
        {
            return this.itemElementNameField;
        }
        set
        {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.paynearme.com/api/pnm_xmlschema_v1_7", IncludeInSchema = false)]
public enum ItemChoiceType
{

    /// <remarks/>
    pnm_order_identifier,

    /// <remarks/>
    pnm_payment_identifier,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.paynearme.com/api/pnm_xmlschema_v1_7")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.paynearme.com/api/pnm_xmlschema_v1_7", IsNullable = false)]
public partial class payment_confirmation_response
{


    public payment_confirmation_responseConfirmation confirmation { get; set; }
    

    private string versionField;

    /// <remarks/>


    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.paynearme.com/api/pnm_xmlschema_v1_7")]
public partial class payment_confirmation_responseConfirmation
{

  
    /// <remarks/>


    public string pnm_order_identifier { get; set; }
   
    



    /// <remarks/>
 
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.paynearme.com/api/pnm_xmlschema_v1_7", IncludeInSchema = false)]
public enum ItemChoiceType1
{

    /// <remarks/>
    pnm_order_identifier,

    /// <remarks/>
    pnm_payment_identifier,
}

/// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.w3.org/2001/XMLSchema-instance", IsNullable = false)]

public partial class payment_authorization_response
{

    
    public string SerializeToXml()
    {
        MemoryStream ms = new MemoryStream();

        XmlSerializerNamespaces ns = new XmlSerializerNamespaces();
        ns.Add("", "");

        new XmlSerializer(typeof(payment_authorization_response)).Serialize(ms, this, ns);
        XmlTextWriter textWriter = new XmlTextWriter(ms, Encoding.UTF8);

        ms = (System.IO.MemoryStream)textWriter.BaseStream;

        return new UTF8Encoding().GetString(ms.ToArray());
    }

    private payment_authorization_responseAuthorization authorizationField;

    private string versionField = "2.0";
    private string xmlField = "";

    /// <remarks/>
    [XmlElementAttribute("authorization")]
    public payment_authorization_responseAuthorization authorization
    {
        get
        {
            return this.authorizationField;
        }
        set
        {
            this.authorizationField = value;
        }
    }

    /// <remarks/>
    [XmlAttributeAttribute()]
    public string version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }

    [XmlAttributeAttribute()]
    public string xmlns
    {
        get
        {
            return this.xmlField;
        }
        set
        {
            this.xmlField = value;
        }
    }
}

/// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class payment_authorization_responseAuthorization
{

    private string pnm_order_identifierField;

    private string pnm_payment_identifierField;

    private payment_authorization_responseAuthorizationAccept_payment accept_paymentField;

    private string receiptField;

    private string memoField;

    private string site_payment_identifierField;

    /// <remarks/>
    public string pnm_order_identifier
    {
        get
        {
            return this.pnm_order_identifierField;
        }
        set
        {
            this.pnm_order_identifierField = value;
        }
    }
    public payment_authorization_responseAuthorizationAccept_payment accept_payment
    {
        get
        {
            return this.accept_paymentField;
        }
        set
        {
            this.accept_paymentField = value;
        }
    }
    public string decline_reason { get; set; }

    public string memo
    {
        get
        {
            return this.memoField;
        }
        set
        {
            this.memoField = value;
        }
    }

    public string receipt
    {
        get
        {
            return this.receiptField;
        }
        set
        {
            this.receiptField = value;
        }
    }
    public string site_payment_identifier
    {
        get
        {
            return this.site_payment_identifierField;
        }
        set
        {
            this.site_payment_identifierField = value;
        }
    }
    /// <remarks/>

    /// <remarks/>
    

    /// <remarks/>
    

    /// <remarks/>
   

    /// <remarks/>


   
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.paynearme.com/api/pnm_xmlschema_v1_7")]
public enum payment_authorization_responseAuthorizationAccept_payment
{

    /// <remarks/>
    yes,

    /// <remarks/>
    no,
}
